name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # セマンティックバージョン範囲構文もしくは厳密なPythonのバージョン
        python-version: '3.x'
        # オプション - x64もしくはx86アーキテクチャ、デフォルトはx64
        architecture: 'x64'
    # 現在のPythonのバージョンを出力して、マトリクスをテストできる
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # このパスは Ubuntu に固有です
        path: ~/.cache/pip
        # 対応する要件ファイルにキャッシュヒットがあるかどうかを確認する
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Script
      run: python3 src/main.py -r -s
    - name: Archive results image
      uses: actions/upload-artifact@v2
      with:
        name: result_image
        path: result.png
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: 1
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [create-or-update-comment][1]

          [1]: https://github.com/peter-evans/create-or-update-comment
        reactions: '+1'

      