name: Python package

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    if: >-
      contains(github.event.comment.body, '/run')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run Script
      run: python3 src/main.py -r -s

    - name: Upload a picture
      uses: devicons/public-upload-to-imgur@v2.2.1
      id: imgur_step
      with:
        path: result.png
        client_id: ${{secrets.IMGUR_CLIENT_ID}}

    - name: Post comment
      uses: peter-evans/create-or-update-comment@v1
      env:
        IMG_URL: ${{ fromJSON(steps.imgur_step.outputs.imgur_urls)[0] }} 
      with:
        issue-number: 1
        body: |
          ![result](${{env.IMG_URL}})

      